"""add location and weather observation tables

Revision ID: eea2630c3da4
Revises: 41ddd7b4ad9d
Create Date: 2025-08-11 21:58:06.440654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eea2630c3da4'
down_revision: Union[str, None] = '41ddd7b4ad9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('admin1', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_locations'))
    )
    op.create_index(op.f('ix_locations_id'), 'locations', ['id'], unique=False)
    op.create_index(op.f('ix_locations_name'), 'locations', ['name'], unique=False)
    op.create_table('weather_observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('temp_c', sa.Float(), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name=op.f('fk_weather_observations_location_id_locations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_weather_observations'))
    )
    op.create_index(op.f('ix_weather_observations_id'), 'weather_observations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weather_observation_1999',
    sa.Column('location_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('ts', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('temp_c', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False),
    sa.Column('source', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('inserted_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['location.location_id'], name='weather_observation_location_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('location_id', 'ts', name='weather_observation_1999_pkey')
    )
    op.create_table('weather_observation_2000',
    sa.Column('location_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('ts', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('temp_c', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False),
    sa.Column('source', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('inserted_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['location.location_id'], name='weather_observation_location_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('location_id', 'ts', name='weather_observation_2000_pkey')
    )
    op.create_table('weather_observation_2004',
    sa.Column('location_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('ts', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('temp_c', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False),
    sa.Column('source', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('inserted_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['location.location_id'], name='weather_observation_location_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('location_id', 'ts', name='weather_observation_2004_pkey')
    )
    op.create_table('weather_observation_1982',
    sa.Column('location_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('ts', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('temp_c', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False),
    sa.Column('source', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('inserted_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['location.location_id'], name='weather_observation_location_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('location_id', 'ts', name='weather_observation_1982_pkey')
    )
    op.create_table('weather_observation_2021',
    sa.Column('location_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('ts', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('temp_c', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False),
    sa.Column('source', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('inserted_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['location.location_id'], name='weather_observation_location_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('location_id', 'ts', name='weather_observation_2021_pkey')
    )
    op.create_table('weather_observation_2024',
    sa.Column('location_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('ts', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('temp_c', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False),
    sa.Column('source', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('inserted_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['location.location_id'], name='weather_observation_location_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('location_id', 'ts', name='weather_observation_2024_pkey')
    )
    op.create_table('weather_observation_1988',
    sa.Column('location_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('ts', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('temp_c', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False),
    sa.Column('source', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('inserted_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['location.location_id'], name='weather_observation_location_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('location_id', 'ts', name='weather_observation_1988_pkey')
    )
    op.create_table('weather_observation_2002',
    sa.Column('location_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('ts', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('temp_c', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False),
    sa.Column('source', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('inserted_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['location.location_id'], name='weather_observation_location_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('location_id', 'ts', name='weather_observation_2002_pkey')
    )
    op.create_table('weather_observation_1987',
    sa.Column('location_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('ts', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('temp_c', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False),
    sa.Column('source', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('inserted_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['location.location_id'], name='weather_observation_location_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('location_id', 'ts', name='weather_observation_1987_pkey')
    )
    op.create_table('weather_observation_1998',
    sa.Column('location_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('ts', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('temp_c', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False),
    sa.Column('source', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('inserted_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['location.location_id'], name='weather_observation_location_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('location_id', 'ts', name='weather_observation_1998_pkey')
    )
    op.create_table('weather_observation_1994',
    sa.Column('location_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('ts', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('temp_c', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False),
    sa.Column('source', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('inserted_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['location.location_id'], name='weather_observation_location_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('location_id', 'ts', name='weather_observation_1994_pkey')
    )
    op.create_table('weather_observation_2020',
    sa.Column('location_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('ts', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('temp_c', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False),
    sa.Column('source', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('inserted_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['location.location_id'], name='weather_observation_location_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('location_id', 'ts', name='weather_observation_2020_pkey')
    )
    op.create_table('weather_observation_2008',
    sa.Column('location_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('ts', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('temp_c', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False),
    sa.Column('source', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('inserted_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['location.location_id'], name='weather_observation_location_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('location_id', 'ts', name='weather_observation_2008_pkey')
    )
    op.create_table('weather_observation_2007',
    sa.Column('location_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('ts', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('temp_c', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False),
    sa.Column('source', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('inserted_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['location.location_id'], name='weather_observation_location_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('location_id', 'ts', name='weather_observation_2007_pkey')
    )
    op.create_table('weather_observation_1984',
    sa.Column('location_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('ts', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('temp_c', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False),
    sa.Column('source', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('inserted_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['location.location_id'], name='weather_observation_location_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('location_id', 'ts', name='weather_observation_1984_pkey')
    )
    op.create_table('weather_observation_1990',
    sa.Column('location_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('ts', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('temp_c', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False),
    sa.Column('source', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('inserted_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['location.location_id'], name='weather_observation_location_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('location_id', 'ts', name='weather_observation_1990_pkey')
    )
    op.create_table('weather_observation_2016',
    sa.Column('location_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('ts', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('temp_c', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False),
    sa.Column('source', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('inserted_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['location.location_id'], name='weather_observation_location_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('location_id', 'ts', name='weather_observation_2016_pkey')
    )
    op.create_table('weather_observation_1986',
    sa.Column('location_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('ts', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('temp_c', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False),
    sa.Column('source', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('inserted_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['location.location_id'], name='weather_observation_location_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('location_id', 'ts', name='weather_observation_1986_pkey')
    )
    op.create_table('weather_observation_2025',
    sa.Column('location_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('ts', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('temp_c', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False),
    sa.Column('source', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('inserted_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['location.location_id'], name='weather_observation_location_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('location_id', 'ts', name='weather_observation_2025_pkey')
    )
    op.create_table('weather_observation_1997',
    sa.Column('location_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('ts', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('temp_c', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False),
    sa.Column('source', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('inserted_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['location.location_id'], name='weather_observation_location_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('location_id', 'ts', name='weather_observation_1997_pkey')
    )
    op.create_table('weather_observation_2009',
    sa.Column('location_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('ts', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('temp_c', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False),
    sa.Column('source', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('inserted_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['location.location_id'], name='weather_observation_location_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('location_id', 'ts', name='weather_observation_2009_pkey')
    )
    op.create_table('weather_observation_2014',
    sa.Column('location_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('ts', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('temp_c', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False),
    sa.Column('source', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('inserted_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['location.location_id'], name='weather_observation_location_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('location_id', 'ts', name='weather_observation_2014_pkey')
    )
    op.create_table('weather_observation_1996',
    sa.Column('location_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('ts', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('temp_c', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False),
    sa.Column('source', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('inserted_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['location.location_id'], name='weather_observation_location_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('location_id', 'ts', name='weather_observation_1996_pkey')
    )
    op.create_table('weather_observation_2023',
    sa.Column('location_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('ts', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('temp_c', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False),
    sa.Column('source', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('inserted_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['location.location_id'], name='weather_observation_location_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('location_id', 'ts', name='weather_observation_2023_pkey')
    )
    op.create_table('weather_observation_2017',
    sa.Column('location_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('ts', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('temp_c', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False),
    sa.Column('source', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('inserted_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['location.location_id'], name='weather_observation_location_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('location_id', 'ts', name='weather_observation_2017_pkey')
    )
    op.create_table('weather_observation_2013',
    sa.Column('location_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('ts', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('temp_c', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False),
    sa.Column('source', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('inserted_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['location.location_id'], name='weather_observation_location_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('location_id', 'ts', name='weather_observation_2013_pkey')
    )
    op.create_table('weather_observation_1993',
    sa.Column('location_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('ts', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('temp_c', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False),
    sa.Column('source', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('inserted_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['location.location_id'], name='weather_observation_location_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('location_id', 'ts', name='weather_observation_1993_pkey')
    )
    op.create_table('weather_observation_2010',
    sa.Column('location_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('ts', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('temp_c', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False),
    sa.Column('source', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('inserted_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['location.location_id'], name='weather_observation_location_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('location_id', 'ts', name='weather_observation_2010_pkey')
    )
    op.create_table('weather_observation_1981',
    sa.Column('location_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('ts', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('temp_c', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False),
    sa.Column('source', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('inserted_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['location.location_id'], name='weather_observation_location_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('location_id', 'ts', name='weather_observation_1981_pkey')
    )
    op.create_table('weather_observation_2015',
    sa.Column('location_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('ts', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('temp_c', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False),
    sa.Column('source', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('inserted_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['location.location_id'], name='weather_observation_location_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('location_id', 'ts', name='weather_observation_2015_pkey')
    )
    op.create_table('weather_observation_1989',
    sa.Column('location_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('ts', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('temp_c', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False),
    sa.Column('source', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('inserted_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['location.location_id'], name='weather_observation_location_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('location_id', 'ts', name='weather_observation_1989_pkey')
    )
    op.create_table('weather_observation_1983',
    sa.Column('location_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('ts', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('temp_c', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False),
    sa.Column('source', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('inserted_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['location.location_id'], name='weather_observation_location_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('location_id', 'ts', name='weather_observation_1983_pkey')
    )
    op.create_table('weather_observation_1985',
    sa.Column('location_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('ts', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('temp_c', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False),
    sa.Column('source', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('inserted_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['location.location_id'], name='weather_observation_location_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('location_id', 'ts', name='weather_observation_1985_pkey')
    )
    op.create_table('weather_observation_1980',
    sa.Column('location_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('ts', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('temp_c', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False),
    sa.Column('source', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('inserted_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['location.location_id'], name='weather_observation_location_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('location_id', 'ts', name='weather_observation_1980_pkey')
    )
    op.create_table('weather_observation_2012',
    sa.Column('location_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('ts', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('temp_c', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False),
    sa.Column('source', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('inserted_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['location.location_id'], name='weather_observation_location_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('location_id', 'ts', name='weather_observation_2012_pkey')
    )
    op.create_table('weather_observation_1991',
    sa.Column('location_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('ts', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('temp_c', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False),
    sa.Column('source', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('inserted_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['location.location_id'], name='weather_observation_location_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('location_id', 'ts', name='weather_observation_1991_pkey')
    )
    op.create_table('weather_observation_2003',
    sa.Column('location_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('ts', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('temp_c', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False),
    sa.Column('source', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('inserted_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['location.location_id'], name='weather_observation_location_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('location_id', 'ts', name='weather_observation_2003_pkey')
    )
    op.create_table('weather_observation_2011',
    sa.Column('location_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('ts', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('temp_c', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False),
    sa.Column('source', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('inserted_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['location.location_id'], name='weather_observation_location_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('location_id', 'ts', name='weather_observation_2011_pkey')
    )
    op.create_table('weather_observation_2006',
    sa.Column('location_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('ts', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('temp_c', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False),
    sa.Column('source', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('inserted_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['location.location_id'], name='weather_observation_location_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('location_id', 'ts', name='weather_observation_2006_pkey')
    )
    op.create_table('weather_observation_2019',
    sa.Column('location_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('ts', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('temp_c', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False),
    sa.Column('source', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('inserted_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['location.location_id'], name='weather_observation_location_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('location_id', 'ts', name='weather_observation_2019_pkey')
    )
    op.create_table('weather_observation_1992',
    sa.Column('location_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('ts', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('temp_c', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False),
    sa.Column('source', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('inserted_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['location.location_id'], name='weather_observation_location_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('location_id', 'ts', name='weather_observation_1992_pkey')
    )
    op.create_table('weather_observation_2001',
    sa.Column('location_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('ts', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('temp_c', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False),
    sa.Column('source', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('inserted_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['location.location_id'], name='weather_observation_location_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('location_id', 'ts', name='weather_observation_2001_pkey')
    )
    op.create_table('weather_observation_2022',
    sa.Column('location_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('ts', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('temp_c', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False),
    sa.Column('source', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('inserted_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['location.location_id'], name='weather_observation_location_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('location_id', 'ts', name='weather_observation_2022_pkey')
    )
    op.create_table('weather_observation_1995',
    sa.Column('location_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('ts', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('temp_c', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False),
    sa.Column('source', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('inserted_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['location.location_id'], name='weather_observation_location_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('location_id', 'ts', name='weather_observation_1995_pkey')
    )
    op.create_table('weather_observation_2005',
    sa.Column('location_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('ts', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('temp_c', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False),
    sa.Column('source', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('inserted_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['location.location_id'], name='weather_observation_location_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('location_id', 'ts', name='weather_observation_2005_pkey')
    )
    op.create_table('weather_observation',
    sa.Column('location_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('ts', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('temp_c', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False),
    sa.Column('source', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('inserted_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['location.location_id'], name='weather_observation_location_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('location_id', 'ts', name='weather_observation_pkey')
    )
    op.create_table('location',
    sa.Column('location_id', sa.BIGINT(), server_default=sa.text("nextval('location_location_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('country_code', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('admin1', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('external_source', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('external_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('location_id', name='location_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('weather_observation_2018',
    sa.Column('location_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('ts', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('temp_c', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False),
    sa.Column('source', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('inserted_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['location.location_id'], name='weather_observation_location_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('location_id', 'ts', name='weather_observation_2018_pkey')
    )
    op.drop_index(op.f('ix_weather_observations_id'), table_name='weather_observations')
    op.drop_table('weather_observations')
    op.drop_index(op.f('ix_locations_name'), table_name='locations')
    op.drop_index(op.f('ix_locations_id'), table_name='locations')
    op.drop_table('locations')
    # ### end Alembic commands ###
